### ISSUE TITLE
[Bug] java.io.IOException during backup

### ISSUE THREAD

**Issue by LondoJI** [machiav3lli/oandbackupx#205]
**Description**
Impossible to backup RetroArch (AArch64) app and data.
A similar behavior happened while trying to backup Microsoft Outlook.
Other apps could be backed up without problems.

**Steps To Reproduce**
1. ... Open OandBackupX
2. ... Backup RetroArch (AArch64) app and data.
3. ... Almost 10 minutes passed after process begun.
4. ... Error appeared as pop-up

"BackupFailedException: java.io.IOException occurred on data backup: java.io.IOException: Entry 'autoconfig/sdl2/8Bitdo NES30 Pro 8Bitdo NES30 Pro.cfg' closed at '0' before the '703' bytes specified in the header were written"

**Expected behavior**
Should backup app and data correctly.

**Screenshots**
![Screenshot_20201108-113439](https://user-images.githubusercontent.com/25232694/98497504-1293f280-223c-11eb-8312-6588492ece1d.jpg)

**System Information(please complete the following information):**
 - Device: Xiaomi Mi A1
 - Android Version: 10
 - ROM: DerpFest 10 (20201012)
 - App's Version: 4.0.0

-------------------------------
**Additional Notes**
* Tried with another software, Swift Backup, worked without problems
* OandBackupX 4.0.0 (GitHub)

**Comment by machiav3lli** [comment]
OABX does compare your backed up data and the live data of the backed up app. This error results from your apps being active and writing to the data while backing up. advanced settings  > STOP/CONT should solve this problem if not try killing the appbefore backup and turning your device's sync off(sync can restart the app's service)

**Comment by LondoJI** [comment]
Thanks friend ;)
Unfortunately, even after following your guide, the same problem persist. Exactly same error happens. Is there any thing I could do to help?

Side note: About killing apps, could be possible to add a switch to kill apps before making a backup?

**Comment by machiav3lli** [comment]
The kill switch was the first strategy adapted before this STOP/CONT pre- and post-processing, but it failed on whole spectrum of different dimensions: data lost, services killed and inconsistent. That's why there's no intention to re-add it.

Oh... you're trying to backup RetroArch, another brother of this is Termux. Both have a network of dynamic dependencies that won't simply stop by killing the app on itself.

**Comment by opusforlife2** [comment]
Same issue with Whatsapp. The STOP/CONT setting works. So does force-stopping the app and turning off internet completely.

**Comment by mase76** [comment]
I have exactly the same behaviour with the Retroarch backup. The old Oandbackup does the backup.

**Comment by tsiflimagas** [comment]
This issue is probably fixed on version 5.0.1.

**Comment by gossbill** [comment]
Still getting this error on 5.0.2. After enabling STOP-CONT two of the failed backups succeeded (Brave, Termux), but VLC still failed.

**Comment by gossbill** [comment]
Tested 5.1.0 and I had no errors on any apps, including VLC! Yay!
It seems that 5.1.0 has finally fixed the problem. May I suggest that this issue be closed and issues.md be updated?

**Comment by opusforlife2** [comment]
@gossbill Thank you for pointing out VLC! Backup indeed succeeds for it now. With this, I have no more apps that face any problems being backed up.

Thank you for this amazing app, @machiav3lli and the rest of the team!

**Comment by mase76** [comment]
No more problems with Retroarch here. Thx.

**Comment by machiav3lli** [comment]
You're welcome

**Comment by MartinX3** [comment]
@machiav3lli I'm getting this issue on 6.0 with the STOP-CONT option for
Chrome
Telegram X
FairMail
Every time.

**Comment by machiav3lli** [comment]
Yeah, some apps has some background services running and modifying the data even when stopped. Some users have reported they were able to solve this through force-killing/disabling and then doing the backup. Even this didn't work for some apps.

**Comment by MartinX3** [comment]
And it's impossible to fix this in the app, or? :(

**Comment by machiav3lli** [comment]
Stopping services than we already do (pid>1000) will touch system services, which are used by OABX including all apps. This is a -little- complicated. But maybe I'll find up a way to handle this more effectively

**Comment by GodKratos** [comment]
I'm also getting this with Spotify, Viber & Messenger. It simply feels like the apps are not being forced closed properly even though I have the STOP-CONT option enabled.
Is it possibly because you stop all apps with pid>1000 at the start of the backup schedule and by the time it gets through backing everything up some of the apps have started up again?
Do you need to individually stop each app before its own backup instead?

**Comment by machiav3lli** [comment]
@GodKratos the problem happens based on the fact that those apps are calling/using  some system services while the backup is running which can't be really stopped (stopping system services can lead to system crashing)

**Comment by GodKratos** [comment]
@machiav3lli if I back them up manually though they don't fail, however almost every time they run in schedule they do fail. That's why I was thinking it might just be the delay between the start of the scheduled backup and the time those apps get backed up that's allowing them time to start up again (if they're killed at the start).

**Comment by machiav3lli** [comment]
@GodKratos hm.. or maybe it's because one backup sends stop while the other sends continue (they run parallel). I'll check this and test a fix in the next neo build. Thanks for the push
